export const REGISTER_TOKEN = 'REG_TOKEN';
export const REGISTER_USER = 'REG_USER';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_PRODUCTS = 'REGISTER_PRODUCTS';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const REGISTER_CATEGORIES = 'REGISTER_CATEGORIES';
export const CLEAR_ALL = 'CLEAR_ALL';
export const REGISTER_LESSONS ="REGISTER_LESSONS";
export const REGISTER_TOTAL_LESSONS ="REGISTER_TOTAL_LESSONS";
export const SET_CURRENT_LESSON ="SET_CURRENT_LESSON";
export const SET_CURRENT_CATEGORY ="SET_CURRENT_CATEGORY";
export const REGISTER_COMMENTS ="REGISTER_COMMENTS";
export const SET_FULLSCREEN ="SET_FULLSCREEN";
export const REGISTER_EMAILCODE = "REGISTER_EMAILCODE"
export const SET_LOGINUSERPASSWORD = "SET_LOGINUSERPASSWORD"
export const SET_LOGINUSEREMAIL = "SET_LOGINUSEREMAIL"

